<?php 
// require $data->path['view'] . 'templates/app.phtml';

$errors = (object) $errors;
$old = (object) $old;

?>


<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Вход</title>
  </head>
  <body>

  <div class="container-fluid mt-5">
    <div class="row justify-content-md-center">
      <h1>Вход</h1>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row justify-content-md-center">
      <div class="col-md-3">

        <?php require $data->app->path['view'] . 'templates/partials/flash.phtml' ?>

        <form action="<?=$data->app->router->pathFor('auth.signin')?>" method="POST" autocomplete="off">
          <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control <?=$errors->email ? 'is-invalid' : ''?>" name="email" id="email" placeholder="Введите email" value="<?=$old->email?>">
            <div class="invalid-feedback"><?=$errors->email ? $errors->email : ''?></div>
          </div>
          <div class="form-group">
            <label for="password">Пароль</label>
            <input type="password" class="form-control <?=$errors->password ? 'is-invalid' : ''?>" name="password" id="password" placeholder="Введите пароль">
            <div class="invalid-feedback"><?=$errors->password ? $errors->password : ''?></div>
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>

          <?=$csrf['field']?>
        </form>

      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>