<?

$key = $data->app->f->currentModule( __DIR__ );
$module = $data->app->mm->get()[$key];
$model = $module['model'];
$moduleName = strtolower($module['config']->name);
$coreui = $data->app->path['root'] . $data->app->path['view'] . 'admin/coreui/';


$errors = (object) $errors;
list($mode, $id) = $data->app->f->getMode($data->request);

$element = $data->app->element;
if ($id) {
  $element = $model::find($id);
}

if (!empty($old)) {
  $old = (object) $old;

  $element->publish = htmlspecialchars($old->publish);
  $element->img = htmlspecialchars($old->img);
  $element->name = htmlspecialchars($old->name);
  $element->text = htmlspecialchars($old->text);
  $element->btn = htmlspecialchars($old->btn);
  $element->href = htmlspecialchars($old->href);
  $element->art = htmlspecialchars($old->art);
}

if ($mode == 'add') {
  $element->publish = 1;
}

?>


<? require $data->app->path['view'] . 'admin/templates/partials/header.phtml' ?>


<div class="app-body">

  <? require $data->app->path['view'] . 'admin/templates/partials/sidebar.phtml' ?>

  <main class="main">

    <?
      $breadcrumbsList = [
        'left' => [
          'Главная' => $data->app->router->pathFor('admin.home'),
          $model::getName()[1] => $data->app->router->pathFor('admin.'.strtolower($key)),
          $data->app->breadcrumbs->last( $data, strtolower($key) ) => ''
        ],
        'right' => [
          'Настройки' => $data->app->router->pathFor('admin.'.$moduleName.'.settings')
        ]
      ];

      echo $data->app->breadcrumbs->get($breadcrumbsList);
    ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <div class="animated fadeIn">

            <?php require $data->app->path['view'] . 'templates/partials/flash.phtml' ?>

            <form action="<?=$data->app->router->pathFor("admin.$moduleName.$mode", ['id' => $id])?>" method="post">

              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Основные</a>
                </li>                
              </ul>

              <div class="tab-content">
                <div class="tab-pane active" id="home" role="tabpanel">

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="publish">Публиковать</label>
                        <select class="form-control select" name="publish" id="publish" value="<?=$element->publish?>">
                          <option value="1">Да</option>
                          <option value="0">Нет</option>
                        </select>
                      </div>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="img">Слайд</label>
                    <textarea class="form-control summernote" id="img" name="img" rows="3"><?=$element->img?></textarea>
                  </div>

                  <div class="form-group">
                    <label for="name">Заголовок</label>
                    <textarea class="form-control summernote" id="name" name="name" rows="3"><?=$element->name?></textarea>
                  </div>

                  <div class="form-group">
                    <label for="text">Описание</label>
                    <textarea class="form-control summernote" id="text" name="text" rows="3"><?=$element->text?></textarea>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="btn">Текст кнопки</label>
                        <input class="form-control" id="btn" type="text" name="btn" value="<?=$element->btn?>">
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="href">Ссылка</label>
                        <input class="form-control" id="href" type="text" name="href" value="<?=$element->href?>">
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="art">Артикул</label>
                        <input class="form-control" id="art" type="text" name="art" value="<?=$element->art?>">
                      </div>
                    </div>
                  </div>
                  <script>
                    $( function() {
                      $( "#art" ).autocomplete({
                        source: [<?=$data->app->f->autocomplete($model, 'art')?>]
                      });
                    } );
                  </script>
                  
                </div>
                
              </div>

              <div class="card">
                <div class="card-footer btn-toolbar justify-content-between">
                  <button class="btn btn-sm btn-primary" type="submit">
                    <i class="fa fa-dot-circle-o"></i> Сохранить</button>

                  <a href="<?=$data->app->router->pathFor('admin.'.$moduleName.'.add')?>" class="btn btn-link" aria-pressed="true">Добавить ещё</a>
                </div>
              </div>

              <?=$csrf['field']?>

            </form>

          </div>
        </div>
        
      </div>
      
    </div>

  </main>
</div>
    
    
<? require $data->app->path['view'] . 'admin/templates/partials/footer.phtml' ?>