<?
$key = $data->app->f->currentModule( __DIR__ );
$module = $data->app->mm->get()[$key];
$model = $module['model'];
$moduleName = strtolower($module['config']->name);
$coreui = $data->app->path['root'] . $data->app->path['view'] . 'admin/coreui/';



$errors = (object) $errors;
list($mode, $id) = $data->app->f->getMode($data->request);

$element = $data->app->element;
if ($id) {
  $element = $model::find($id);
}

if (!empty($old)) {
  $old = (object) $old;

  $element->namespace = htmlspecialchars($old->namespace);
  $element->tab = htmlspecialchars($old->tab);
  $element->name = htmlspecialchars($old->name);
  $element->description = htmlspecialchars($old->description);
  $element->value = htmlspecialchars($old->value);
  $element->type = htmlspecialchars($old->type);
  $element->code = htmlspecialchars($old->code);
  $element->values = htmlspecialchars($old->values);
}

?>


<? require $data->app->path['view'] . 'admin/templates/partials/header.phtml' ?>


<div class="app-body">

  <? require $data->app->path['view'] . 'admin/templates/partials/sidebar.phtml' ?>

  <main class="main">

    <?
      $breadcrumbsList = [
        'left' => [
          'Главная' => $data->app->router->pathFor('admin.home'),
          $model::getName()[1] => $data->app->router->pathFor('admin.'.strtolower($key)),
          $data->app->breadcrumbs->last( $data, strtolower($key) ) => ''
        ]        
      ];

      echo $data->app->breadcrumbs->get($breadcrumbsList);
    ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <div class="animated fadeIn">

            <?php require $data->app->path['view'] . 'templates/partials/flash.phtml' ?>

            <form action="<?=$data->app->router->pathFor("admin.$moduleName.$mode", ['id' => $id])?>" method="post">

              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Основные</a>
                </li>
              </ul>

              <div class="tab-content">
                <div class="tab-pane active" id="home" role="tabpanel">

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="type">Тип опции <i class="text-danger">*</i></label>
                        <select class="form-control <?=$errors->type ? 'is-invalid' : ''?> select" name="type" id="type" value="<?=$element->type?>">
                          <option value="">Выберите тип опции</option>
                          <option value="input">Input</option>
                          <option value="textarea">Textarea</option>
                          <option value="select">Select</option>
                        </select>
                        <div class="invalid-feedback"><?=$errors->type ? $errors->type : ''?></div>
                      </div>
                    </div>
                  </div>

                  <div class="row js-values-row d-none">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="values">Значения</label>
                        <input class="form-control <?=$errors->values ? 'is-invalid' : ''?>" id="values" type="text" name="values" value="<?=$element->values?>">
                        <div class="invalid-feedback"><?=$errors->values ? $errors->values : ''?></div>
                      </div>
                    </div>
                  </div>
                  <script>
                    $( function() {
                      $( "#values" ).autocomplete({
                        source: [<?=$data->app->f->autocomplete($model, 'values')?>]
                      });
                    } );
                  </script>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="code">Служебное имя <i class="text-danger">*</i></label>
                        <input class="form-control <?=$errors->code ? 'is-invalid' : ''?>" id="code" type="text" name="code" value="<?=$element->code?>">
                        <div class="invalid-feedback"><?=$errors->code ? $errors->code : ''?></div>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="name">Название <i class="text-danger">*</i></label>
                        <input class="form-control <?=$errors->name ? 'is-invalid' : ''?>" id="name" type="text" name="name" value="<?=$element->name?>" >
                        <div class="invalid-feedback"><?=$errors->name ? $errors->name : ''?></div>
                      </div>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="description">Описание <i class="text-danger">*</i></label>
                    <textarea class="form-control <?=$errors->description ? 'is-invalid' : ''?>" id="description" name="description" rows="3"><?=$element->description?></textarea>
                    <div class="invalid-feedback"><?=$errors->description ? $errors->description : ''?></div>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="namespace">Категория <i class="text-danger">*</i></label>
                        <input class="form-control <?=$errors->namespace ? 'is-invalid' : ''?>" id="namespace" type="text" name="namespace" value="<?=$element->namespace?>">
                        <div class="invalid-feedback"><?=$errors->namespace ? $errors->namespace : ''?></div>
                      </div>
                    </div>
                  </div>
                  <script>
                    $( function() {
                      $( "#namespace" ).autocomplete({
                        source: [<?=$data->app->f->autocomplete($model, 'namespace')?>]
                      });
                    } );
                  </script>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="tab">Таб <i class="text-danger">*</i></label>
                        <input class="form-control <?=$errors->tab ? 'is-invalid' : ''?>" id="tab" type="text" name="tab" value="<?=$element->tab?>">
                        <div class="invalid-feedback"><?=$errors->tab ? $errors->tab : ''?></div>
                      </div>
                    </div>
                  </div>
                  <script>
                    $( function() {
                      $( "#tab" ).autocomplete({
                        source: [<?=$data->app->f->autocomplete($model, 'tab')?>]
                      });
                    } );
                  </script>

                  <div class="form-group">
                    <label for="value">Значение</label>
                    <textarea class="form-control <?=$errors->value ? 'is-invalid' : ''?>" id="value" name="value" rows="7"><?=$element->value?></textarea>
                    <div class="invalid-feedback"><?=$errors->value ? $errors->value : ''?></div>
                  </div>
                  
                </div>
              </div>

              <div class="card">
                <div class="card-footer btn-toolbar justify-content-between">
                  <button class="btn btn-sm btn-primary" type="submit">
                    <i class="fa fa-dot-circle-o"></i> Сохранить</button>

                  <a href="<?=$data->app->router->pathFor('admin.'.$moduleName.'.add')?>" class="btn btn-link" aria-pressed="true">Добавить ещё</a>

                </div>
              </div>

              <?=$csrf['field']?>

            </form>

          </div>
        </div>
        
      </div>
      
    </div>

  </main>
</div>
    
    
<? require $data->app->path['view'] . 'admin/templates/partials/footer.phtml' ?>