    <footer class="app-footer">
      <div>
        <a href="javascript:void(0)">BatLab</a>
        <span>&copy; 2019 batLab.</span>
      </div>
      <div class="ml-auto">
        <span>Powered by</span>
        <a href="javascript:void(0)">BatLab</a>
      </div>
    </footer>

    <!-- CoreUI and necessary plugins-->
    <!-- <script src="<?=$coreui?>vendors/jquery/js/jquery.min.js"></script> -->
    <script src="<?=$coreui?>vendors/popper.js/js/popper.min.js"></script>
    <script src="<?=$coreui?>vendors/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?=$coreui?>vendors/pace-progress/js/pace.min.js"></script>
    <script src="<?=$coreui?>vendors/perfect-scrollbar/js/perfect-scrollbar.min.js"></script>
    <script src="<?=$coreui?>vendors/@coreui/coreui/js/coreui.min.js"></script>
    
    <!-- Plugins and scripts required by this view-->
    <script src="<?=$coreui?>js/colors.js"></script>
    <script src="<?=$coreui?>js/common.js"></script>

    
    <?
      // Plugins script required by this view
      echo $data->app->plugin->addJs();
    ?>
    

  </body>
</html>