<?php

  use App\Filter\Filter;
  use App\Menu\Menu;
  use App\Modules\Shorts\ModelFilterBuilder\ShortFilter;
  use App\Modules\Options\ModelFilterBuilder\OptionFilter;
  use App\Design\PublicBuilder;

  $template = new PublicBuilder( $data );

  $tempPath = $data->app->path['view'] . 'public/'. $data->app->settings['public']['template'] .'/';
  $partials = $data->app->path['view'] . 'public/partials/';
  $route = $data->request->getAttribute('route');

?>

<?php require $partials . 'head.phtml' ?>

  <?php require $partials . 'header.phtml' ?>

  
  

<?php require $partials . 'footer.phtml' ?>