<?php
  $model = $data->model;

  use App\Modules\Options\ModelFilterBuilder\OptionFilter;
  use App\Modules\Pages\Models\Page;
  use App\Filter\Filter;
  use App\Design\PublicBuilder;

  $template = new PublicBuilder( $data );

  $tempPath = $data->app->path['root'] . $data->app->path['view'] . 'public/'. $data->app->settings['public']['template'] .'/';
  $partials = $data->app->path['view'] . 'public/partials/';

  require $partials . 'head.phtml';
  require $partials . 'header.phtml';
?>

  <div class="page__container">
    <div class="page__row">
      <div class="page__col">
        <h1><?=$model->name?></h1>
        <?=new Filter(htmlspecialchars_decode($model->text), $data->app);?>
      </div>
    </div>
  </div>

<?php require $partials . 'footer.phtml' ?>