<?php

use App\Modules\Pages\Models\Page;
use App\Filter\Filter;

$tempPath = $data->app->path['view'] . 'public/'. $data->app->settings['public']['template'] .'/';
$partials = $data->app->path['view'] . 'public/partials/';

$p = Page::where('url', '=', $slug)->get()[0];

?>

  <?php require $partials . 'head.phtml' ?>

  <?php require $partials . 'header.phtml' ?>

  <section class="inner">
    <div class="wrap">
      <div class="contacts__title wow fadeInDown">
        <h1 class="style-dark tac"><?=$p->name?></h1>
      </div>
      <div class="contacts__content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12">
              <?=new Filter($p->text);?>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <?php require $partials . 'footer.phtml' ?>

  <?php //require $partials . 'modal.phtml' ?>

    
  </div>
  <!-- <script src="<?=$tempPath?>app.js"></script> -->
  <?=$data->app->plugin->addJs()?>
</body>
</html>