<?

$key = $data->app->f->currentModule( __DIR__ );
$module = $data->app->mm->get()[$key];
$model = $module['model'];
$moduleName = strtolower($module['config']->name);
$coreui = $data->app->path['root'] . $data->app->path['view'] . 'admin/coreui/';


$errors = (object) $errors;
list($mode, $id) = $data->app->f->getMode($data->request);

$element = $data->app->element;
if ($id) {
  $element = $model::find($id);
}

if (!empty($old)) {
  $old = (object) $old;

  $element->img = $old->img;
  $element->name = $old->name;
  $element->post = $old->post;
  $element->title = $old->title;
  $element->text = $old->text;
}

?>


<? require $data->app->path['view'] . 'admin/templates/partials/header.phtml' ?>


<div class="app-body">

  <? require $data->app->path['view'] . 'admin/templates/partials/sidebar.phtml' ?>

  <main class="main">

    <?
      $breadcrumbsList = [
        'left' => [
          'Главная' => $data->app->router->pathFor('admin.home'),
          $model::getName()[1] => $data->app->router->pathFor('admin.'.strtolower($key)),
          $data->app->breadcrumbs->last( $data, strtolower($key) ) => ''
        ],
        'right' => [
          'Настройки' => $data->app->router->pathFor('admin.'.$moduleName.'.settings')
        ]
      ];

      echo $data->app->breadcrumbs->get($breadcrumbsList);
    ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <div class="animated fadeIn">

            <?php require $data->app->path['view'] . 'templates/partials/flash.phtml' ?>

            <form action="<?=$data->app->router->pathFor("admin.$moduleName.$mode", ['id' => $id])?>" method="post">

              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Основные</a>
                </li>
              </ul>

              <div class="tab-content">
                <div class="tab-pane active" id="home" role="tabpanel">

                  <div class="form-group">
                    <label for="img">Картинка</label>
                    <textarea class="form-control summernote" id="img" name="img" rows="3"><?=$element->img?></textarea>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="name">Имя</label>
                        <input class="form-control" id="name" type="text" name="name" value="<?=$element->name?>" >
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="post">Должность</label>
                        <input class="form-control" id="post" type="text" name="post" value="<?=$element->post?>">
                      </div>
                    </div>
                  </div>
                  
                  <div class="form-group">
                    <label for="title">Заголовок</label>
                    <textarea class="form-control" id="title" name="title" rows="3"><?=$element->title?></textarea>
                  </div>

                  <div class="form-group">
                    <label for="text">Отзыв</label>
                    <textarea class="form-control summernote" id="text" name="text" rows="3"><?=$element->text?></textarea>
                  </div>
                  
                </div>                
              </div>

              <div class="card">
                <div class="card-footer btn-toolbar justify-content-between">
                  <button class="btn btn-sm btn-primary" type="submit">
                    <i class="fa fa-dot-circle-o"></i> Сохранить</button>

                  <a href="<?=$data->app->router->pathFor('admin.'.$moduleName.'.add')?>" class="btn btn-link" aria-pressed="true">Добавить ещё</a>
                </div>
              </div>

              <?=$csrf['field']?>

            </form>

          </div>
        </div>
        
      </div>
      
    </div>

  </main>
</div>
    
    
<? require $data->app->path['view'] . 'admin/templates/partials/footer.phtml' ?>