<?
  use App\Modules\Options\ModelFilterBuilder\OptionFilter;
  use App\Modules\Shorts\ModelFilterBuilder\ShortFilter;
  use App\Menu\Menu;

  $route = $data->request->getAttribute('route');  
?>

<header id="header" class="page-header <?=($route->getName()=='home' || in_array($slug, $listPages))?'page-header--gradient':''?>" role="banner">

  <?=OptionFilter::code('phone1')?>
  <?=OptionFilter::code('email')?>
  <?=$data->app->router->pathFor('home')?>
  <?=OptionFilter::code('title')?>
  <?=ShortFilter::get(1, 'src')?>
  <?=new Menu($data, 'main')?>
    
</header>