<?

$key = $data->app->f->currentModule( __DIR__ );
$module = $data->app->mm->get()[$key];
$model = $module['model'];
$moduleName = strtolower($module['config']->name);
$coreui = $data->app->path['root'] . $data->app->path['view'] . 'admin/coreui/';


$errors = (object) $errors;
list($mode, $id) = $data->app->f->getMode($data->request);

$element = $data->app->element;
if ($id) {
  $element = $model::find($id);
}

if (!empty($old)) {
  $old = (object) $old;

  $element->publish = htmlspecialchars($old->publish);
  $element->name = htmlspecialchars($old->name);
  $element->sort = htmlspecialchars($old->sort);
  $element->url = htmlspecialchars($old->url);
  $element->art = htmlspecialchars($old->art);
  $element->text = htmlspecialchars($old->text);
  $element->title = htmlspecialchars($old->title);
  $element->description = htmlspecialchars($old->description);
  $element->keywords = htmlspecialchars($old->keywords);
  $element->seo_title = htmlspecialchars($old->seo_title);
  $element->seo_text = htmlspecialchars($old->seo_text);
}

?>


<? require $data->app->path['view'] . 'admin/templates/partials/header.phtml' ?>


<div class="app-body">

  <? require $data->app->path['view'] . 'admin/templates/partials/sidebar.phtml' ?>

  <main class="main">

    <?
      $breadcrumbsList = [
        'left' => [
          'Главная' => $data->app->router->pathFor('admin.home'),
          $model::getName()[1] => $data->app->router->pathFor('admin.'.strtolower($key)),
          $data->app->breadcrumbs->last( $data, strtolower($key) ) => ''
        ],
        'right' => [
          'Настройки' => $data->app->router->pathFor('admin.'.$moduleName.'.settings')
        ]
      ];

      echo $data->app->breadcrumbs->get($breadcrumbsList);
    ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <div class="animated fadeIn">

            <?php require $data->app->path['view'] . 'templates/partials/flash.phtml' ?>

            <form action="<?=$data->app->router->pathFor("admin.$moduleName.$mode", ['id' => $id])?>" method="post">

              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Основные</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#seo" role="tab" aria-controls="seo" aria-selected="false">Seo</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#seo-block" role="tab" aria-controls="seo-block" aria-selected="false">Seo-блок</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#fields" role="tab" aria-controls="fields" aria-selected="false">Дополнительные поля</a>
                </li>
              </ul>

              <div class="tab-content">
                <div class="tab-pane active" id="home" role="tabpanel">

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="publish">Публиковать</label>
                        <select class="form-control select" name="publish" id="publish" value="<?=$element->publish?>">
                          <option value="1">Да</option>
                          <option value="0">Нет</option>
                        </select>
                      </div>
                    </div>
                  </div>

                  <div class="row" style="display: none;">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="sort">Сортировка <i class="text-danger">*</i></label>
                        <input class="form-control <?=$errors->sort ? 'is-invalid' : ''?>" id="sort" type="text" name="sort" value="<?=$element->sort?>" >
                        <div class="invalid-feedback"><?=$errors->sort ? $errors->sort : ''?></div>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="name">Название <i class="text-danger">*</i></label>
                        <input class="form-control <?=$errors->name ? 'is-invalid' : ''?>" id="name" type="text" name="name" value="<?=$element->name?>" >
                        <div class="invalid-feedback"><?=$errors->name ? $errors->name : ''?></div>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="url">Ссылка <i class="text-danger">*</i></label>
                        <input class="form-control <?=$errors->url ? 'is-invalid' : ''?>" id="url" type="text" name="url" value="<?=$element->url?>">
                        <div class="invalid-feedback"><?=$errors->url ? $errors->url : ''?></div>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12 col-md-4">
                      <div class="form-group">
                        <label for="art">Артикул</label>
                        <input class="form-control <?=$errors->art ? 'is-invalid' : ''?>" id="art" type="text" name="art" value="<?=$element->art?>">
                        <div class="invalid-feedback"><?=$errors->art ? $errors->art : ''?></div>
                      </div>
                    </div>
                  </div>
                  <script>
                    $( function() {
                      $( "#art" ).autocomplete({
                        source: [<?=$data->app->f->autocomplete($model, 'art')?>]
                      });
                    } );
                  </script>

                  <div class="form-group">
                    <label for="text">Контент</label>
                    <textarea class="form-control summernote" id="text" name="text" rows="9"><?=$element->text?></textarea>
                  </div>
                  
                </div>
                <div class="tab-pane" id="seo" role="tabpanel">
                  
                  <div class="form-group">
                    <label for="title">Мета заголовок</label>
                    <textarea class="form-control" id="title" name="title" rows="2"><?=$element->title?></textarea>
                  </div>

                  <div class="form-group">
                    <label for="description">Мета описание</label>
                    <textarea class="form-control" id="description" name="description" rows="2"><?=$element->description?></textarea>
                  </div>

                  <div class="form-group">
                    <label for="keywords">Мета ключевые слова</label>
                    <textarea class="form-control" id="keywords" name="keywords" rows="2"><?=$element->keywords?></textarea>
                  </div>

                </div>
                <div class="tab-pane" id="seo-block" role="tabpanel">
                  
                  <div class="form-group">
                    <label for="seo_title">Заголовок</label>
                    <textarea class="form-control" id="seo_title" name="seo_title" rows="2"><?=$element->seo_title?></textarea>
                  </div>

                  <div class="form-group">
                    <label for="seo_text">Текст</label>
                    <textarea class="form-control summernote" id="seo_text" name="seo_text" rows="9"><?=$element->seo_text?></textarea>
                  </div>

                </div>
                <div class="tab-pane" id="fields" role="tabpanel">
                  <div class="form-group">
                    <label for="min_text">Малое описание</label>
                    <textarea class="form-control summernote" id="min_text" name="min_text" rows="9"><?=$element->min_text?></textarea>
                  </div>
                </div>
              </div>

              <div class="card">
                <div class="card-footer btn-toolbar justify-content-between">
                  <button class="btn btn-sm btn-primary" type="submit">
                    <i class="fa fa-dot-circle-o"></i> Сохранить</button>

                  <a href="<?=$data->app->router->pathFor('admin.'.$moduleName.'.add')?>" class="btn btn-link" aria-pressed="true">Добавить ещё</a>

                </div>
              </div>

              <?=$csrf['field']?>

            </form>

          </div>
        </div>
        
      </div>
      
    </div>

  </main>
</div>
    
    
<? require $data->app->path['view'] . 'admin/templates/partials/footer.phtml' ?>