<?

$key = $data->app->f->currentModule( __DIR__ );
$module = $data->app->mm->get()[$key];
$model = $module['model'];
$moduleName = strtolower($module['config']->name);
$coreui = $data->app->path['root'] . $data->app->path['view'] . 'admin/coreui/';

?>


<? require $data->app->path['view'] . 'admin/templates/partials/header.phtml' ?>


<div class="app-body">

  <? require $data->app->path['view'] . 'admin/templates/partials/sidebar.phtml' ?>

  <main class="main">

    <?
      $breadcrumbsList = [
        'left' => [
          'Главная' => $data->app->router->pathFor('admin.home'),
          $model::getName()[1] => $data->app->router->pathFor('admin.'.strtolower($key)),
          'Настройки' => ''
        ],
        'right' => [
          'Настройки' => $data->app->router->pathFor('admin.'.$moduleName.'.settings')
        ]
      ];

      echo $data->app->breadcrumbs->get($breadcrumbsList);
    ?>

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <div class="animated fadeIn">

            <?php require $data->app->path['view'] . 'templates/partials/flash.phtml' ?>

            <form action="<?=$data->app->router->pathFor("admin.$moduleName.settings")?>" method="post">

              <?
                echo $data->app->AdminBuilder->getDynamicField("admin.$moduleName.settings");
                echo $csrf['field'];
              ?>

            </form>

          </div>
        </div>
        
      </div>
      
    </div>

  </main>
</div>
    
    
<? require $data->app->path['view'] . 'admin/templates/partials/footer.phtml' ?>